####################################
### BASE
####################################
FROM node:14.15.1-alpine3.12 as base

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# add app dependencies
COPY package.json ./
COPY package-lock.json ./

# run npm install dependencies
RUN npm install

# add app
COPY . ./

####################################
### DEV
####################################
FROM base as dev

# expose app port
EXPOSE 3000

ENV PORT 3000

# start app
CMD ["nodemon"]