version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.12.16
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - EDGE_PORT=4566
      - SERVICES=sqs,events,cloudformation,dynamodb,s3,apigateway,lambda
      - DEBUG=1
    ports:
      - '4566:4566'
    volumes:
      - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
