version: '3.8'

services:
  backend:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    network_mode: host
    stdin_open: true