version: 0.2

phases:
  build:
    commands:
      - echo updating Deployment status badge to successful
      - mkdir badges && cd ./badges
      - touch badge-deployment-status.svg
      - curl -s "https://img.shields.io/badge/Pipeline%20Status-passed-green.svg" > badge-deployment-status.svg
      - aws s3 sync . s3://$S3_EXTRAS_BUCKET/badges --acl public-read
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" badge-deployment-status.svg s3://$S3_EXTRAS_BUCKET/badges/badge-deployment-status.svg
      - cd ..
      - rm -rf ./badges
