server:
  origin: 'http://localhost:8081'
  port: 3001
  prefix: 'api'
  payload:
    limit: '50mb'

workflow:
  domain: http://localhost:8081
  batchLimit: 10

externalServices:
  imapEndpoint: http://localhost:3003
  ocrEndpoint: http://localhost:3002

aws:
  accessKeyId: 'mock'
  secretAccessKey: 'mock'
  region: 'ap-southeast-2'
# use host.docker.internal if we run the workflow-api image container, hence use localhost if run directly
  local: 'http://localhost:4566'
  kms:
    keyId: '605d7185-79e0-4364-b704-70a366d7d23a'
    alias: 'alias/Workflow'

s3:
  bucket: 'sample'
  expiresIn: 86400

dynamodb:
  local: 'http://host.docker.internal:4566'
  schema:
    workflow: 'workflow'
    workflowVersions: 'workflow-versions'
    workflowExecutions: 'workflow-executions'
    integrations: 'integrations'
    integrationTokens: 'integration-tokens'
    authOrganizations: 'auth-organizations'
    authUsers: 'auth-users'
    apigwAuthorizer: 'apigw-authorizer'
    resources: 'resources'

jwt:
  secret: 'TokenSecret'
  accessToken:
    expiresIn: '30min'
  refreshToken:
    expiresIn: '12h'
    maxAge: 43200000
    sameSite: 'None'
  emailToken:
    expiresIn: '1h'

email:
  gmail:
    user: 'some@some.com'
    password: 'somePassword'

apiGateway:
  endpoint: 'http://host.docker.internal:4566'
  usagePlanName: 'Workflow Usage Plan'
  restApiName: 'Workflow API'
  restApiResource: 'trigger'
  description: 'Workflow API Deployment'

cache:
  expiresIn: 300000

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'

files:
  dir: './uploads/'

sqs:
  endpoint: 'http://host.docker.internal:4566'
  queueName: 'WORKFLOW_QUEUE'
  queueUrl: 'http://host.docker.internal:4566/000000000000/WORKFLOW_QUEUE'
  queueError: 'WORKFLOW_QUEUE_ERROR'
  queueErrorUrl: 'http://host.docker.internal:4566/000000000000/WORKFLOW_QUEUE_ERROR'
  maxRetriesLimit: 3
  maxRetriesIntervalSeconds:
    - 5
    - 15
    - 30

eventBridge:
  endpoint: 'http://host.docker.internal:4566'

lambda:
  webServiceFunctionName: 'srvls-generic-svc-local-genericFunction'

mailgun:
  test: false
  apiKey: '839b890b5e34d37dfc5c4564170a40e5-2bf328a5-8ef298c2'
  domain: 'sandboxfce6122a4b56445895c58d09b9b5496b.mailgun.org'
  fromEmail: 'CoWo Team <support@cowo.io>'
  toEmail: 'seth@lambdas.io'
  ccEmail: 'notifications@lambdas.io'

stripe:
  sk: 'test_key'

oauth:
  redirectUriPath: 'https://workflow-api.lambdas.io'
authBeEndpoint: 'https://workflow-api.lambdas.io/api/graphql'
