server:
  origin: http://localhost:3001
  port: 3000
  prefix: 'api'
  payload:
    limit: '50mb'

externalServices:
  imapEndpoint: http://localhost:3001
  ocrEndpoint: http://localhost:3002

aws:
  accessKeyId: 'sampleAccessKeyId'
  secretAccessKey: 'sampleSecretAccessKey'
  region: 'ap-southeast-2'
  local: 'http://localhost:4566'

dynamodb:
  local: 'http://localhost:4566'
  schema:
    workflow: 'workflow'
    workflowOrganization: 'workflow_organizations'

jwt:
  secret: 'TokenSecret'
  accessToken:
    expiresIn: '30min'
  refreshToken:
    expiresIn: '12h'
    maxAge: 43200000

apiGateway:
  endpoint: 'http://localhost:4566'
  usagePlanName: 'Workflow Usage Plan'
  restApiName: 'Workflow API'
  restApiResource: 'trigger'
  description: 'Workflow API Deployment'

cache:
  expiresIn: 300000

logLevel:
  - 'log'
  - 'debug'

files:
  dir: './uploads/'

sqs:
  endpoint: 'http://localhost:4566'
  queueName: 'WORKFLOW_QUEUE'
  queueUrl: 'http://localhost:4566/000000000000/WORKFLOW_QUEUE'
  queueError: 'WORKFLOW_QUEUE_ERROR'
  queueErrorUrl: 'http://localhost:4566/000000000000/WORKFLOW_QUEUE_ERROR'
  maxRetriesLimit: 3
  maxRetriesIntervalSeconds:
    - 5
    - 15
    - 30

eventBridge:
  endpoint: 'http://localhost:4566'

lambda:
  webServiceFunctionName: 'srvls-generic-svc-local-genericFunction'

mailgun:
  test: false
  apiKey: '2346287e8a0e68a2f4d426cb6c74d01b-73e57fef-1687955e'
  domain: 'sandboxbf87ded23ebb4b8d800d5c56edaadc3c.mailgun.org'
  fromEmail: 'sourceEmail@gmail.com'
  toEmail: 'printerEmail@gmail.com'
  ccEmail: 'ccEmail@gmail.com'
