authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: '762ffd9e-f313-4ac0-a20a-1c78fc97f9b7'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'

integrations:
  twilio:
    sid: 'ACac1efc8f48058add76f327cd30c0f328'
  sendle:
    api: 'sandbox_tVXmzStvRsn38xHfZ8mTnzDr'
    url: 'sandbox'