authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: 'dfe5bcbc-e594-495b-a0a5-1992c1dc3186'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'
