authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: '27de59d2-8e83-402a-adf4-64e001bfd362'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'
