authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: '2d41b5b8-2fe7-4c69-8f42-6870aa8360bc'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'

integrations:
  twilio:
    sid: 'ACac1efc8f48058add76f327cd30c0f328'
  sendle:
    api: 'sandbox_tVXmzStvRsn38xHfZ8mTnzDr'
    url: 'sandbox'

apiGateway:
  resourceId: '5oskav0j4h'
  stage: 'local'

lambda:
  webServiceFunctionName: 
  apigatewayFunction: 