authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: 'e7c9dba9-4dd8-4de5-9418-dd13f6f527fa'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'
