authBeEndpoint: 'http://localhost:3001/api/graphql'
oauth:
  redirectUriPath: 'http://localhost:3001'
aws:
  kms:
    keyId: '9e9ebe9d-f617-4956-a376-34a6239ff245'
    alias: 'alias/Workflow'

jwt:
  secret: 'topSecret51'

logLevel:
  - 'log'
  - 'error'
  - 'warn'
  - 'info'
  - 'debug'

integrations:
  twilio:
    sid: 'ACac1efc8f48058add76f327cd30c0f328'
  sendle:
    api: 'sandbox_tVXmzStvRsn38xHfZ8mTnzDr'
    url: 'sandbox'