server:
  origin: https://workflow.lambdas.io

workflow:
  domain: https://workflow.lambdas.io

aws:
  local: #empty to overide default.yml local endpoint
  accessKeyId: 'AKIA5LDPWSIID6U5NYVN'
  secretAccessKey: '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'

dynamodb:
   local: #empty to overide default.yml local endpoint


sqs:
  queueUrl: 'https://sqs.ap-southeast-2.amazonaws.com/917209780752/WORKFLOW_QUEUE'
  queueErrorUrl: '  https://sqs.ap-southeast-2.amazonaws.com/917209780752/WORKFLOW_QUEUE_ERROR'

lambda:
  webServiceFunctionName: 'srvls-generic-svc-production-genericFunction'

integrations:
  twilio:
    sid: 'ACac1efc8f48058add76f327cd30c0f328'
  sendle:
    api: 'sandbox_tVXmzStvRsn38xHfZ8mTnzDr'
    url: 'api'