server:
  origin: https://workflow.lambdas.io

workflow:
  domain: https://workflow.lambdas.io

aws:
  local: #empty to overide default.yml local endpoint
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

dynamodb:
   local: #empty to overide default.yml local endpoint

stripe:
  sk: ${STRIPE_SECRET_KEY}

apiGateway:
  resourceId: '5oskav0j4h'

email:
  gmail:
    user: ${NODEMAILER_GMAIL_USERNAME}
    password: ${NODEMAILER_GMAIL_PASSWORD}

sqs:
  queueUrl: 'https://sqs.ap-southeast-2.amazonaws.com/917209780752/WORKFLOW_QUEUE'
  queueErrorUrl: '  https://sqs.ap-southeast-2.amazonaws.com/917209780752/WORKFLOW_QUEUE_ERROR'

lambda:
  webServiceFunctionName: 'srvls-generic-svc-production-genericFunction'

integrations:
  twilio:
    sid: 'ACac1efc8f48058add76f327cd30c0f328'
  sendle:
    api: 'sandbox_tVXmzStvRsn38xHfZ8mTnzDr'
    url: 'api'