db:
  host: 'localhost'
  database: 'sample'
  username: 'root'
  password: '12345'
  dropSchema: true
  migrationsRun: true

dynamodb:
  schema:
    workflowExecutions: 'workflow_executions_test'
    workflowVersions: 'workflow_versions_test'
    workflowSteps: 'workflow_steps_test'

jwt:
  secret: 'topSecretTest51'

files:
  dir: './test/uploads/'