authBeEndpoint: 'http://localhost:3001/api/graphql'

dynamodb:
  schema:
    workflow: 'workflow_test'
    workflowOrganization: 'workflow_organizations_test'
    workflowVersions: 'workflow-versions_test'
    workflowExecutions: 'workflow-executions_test'

jwt:
  secret: 'topSecretTest51'

files:
  dir: './test/uploads/'
