db:
  host: 'localhost'
  database: 'sample'
  username: 'root'
  password: '12345'
  dropSchema: true
  migrationsRun: true

jwt:
  secret: 'topSecretTest51'

files:
  dir: './test/uploads/'

aws:
  dynamodb:
    schema:
      workflowVersions: 'workflow_versions_test'
      workflowSpecs: 'workflow_specs_test'