db:
  host: 'localhost'
  database: 'sample'
  username: 'root'
  password: '12345'
  dropSchema: true
  migrationsRun: true

dynamodb:
  schema:
    workflowVersions: 'workflow_versions_test'
    workflowSpecs: 'workflow_specs_test'

jwt:
  secret: 'topSecretTest51'

files:
  dir: './test/uploads/'