db:
  host: 'localhost'
  database: 'sample'
  username: 'root'
  password: '12345'
  dropSchema: true
  migrationsRun: true

dynamodb:
  schema:
    workflow: 'workflow_test'
    workflowOrganization: 'workflow_organizations_test'

jwt:
  secret: 'topSecretTest51'

files:
  dir: './test/uploads/'